name: movie_explorer
description: A beautiful Flutter application to explore movies using TMDB API.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.2.1 # For API calls
  cached_network_image: ^3.3.1 # For efficient image loading
  shimmer: ^3.0.0 # For loading animations
  provider: ^6.1.2 # For state management
  go_router: ^14.0.0 # For navigation
  hive: ^2.2.3 # Hive database
  hive_flutter: ^1.1.0 # Hive Flutter integration
  # Firebase dependencies
  firebase_core: ^2.30.1 # Firebase core
  firebase_auth: ^4.19.4 # Firebase Authentication
  google_sign_in: ^6.2.1 # Google Sign-In

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  hive_generator: ^2.0.1 # For generating Hive adapters
  build_runner: ^2.4.9 # For running code generation

flutter:
  uses-material-design: true